machine learning basics/Readme.md
machine learning basics/gradient_descent.py
python basics/contributors.md
python basics/for_loop.py
python basics/while_loop.py
while_loop.py

Created for_loop.py and while_loop.py.
Also created contributors.md

Created files 

---

python basics/strings.py

https://github.com/hr21/DataQuest/issues/3

[add] manejo strings

---

python basics/simple_guessing_game.py

Adds a simple game to show a for loop, the input function, random number generation and conditional statements. Also shows try/except for capturing exceptions.

Add a simple number guessing game

---

python basics/contributors.md
python basics/slicing.py

Slicing examples for #3! If you would like more examples let me know and I will commit some more.

added slicing examples

---

python basics/basic_ops.py

Arithmetic operations are added with comments

Added basic operation in python

---

python basics/regex.py

Added tutorial for pattern matching with regex

---

python basics/string_manipulation.py

I know there's a basic strings.py file and I can modify it if you prefer, but I made a new one completely in english.
Not sure if that easy to understand, if not or some concept is wrong let me know.

Add string manipulation in python.

---

python basics/Readme.md

I append some resources and found a small typo in README file

Added some resources

---

machine learning basics/knn.R
machine learning basics/knn.py

Hi, 
I have added K-Nearest Neighbors (K-NN) code in python and R.
Regards

Added K-Nearest Neighbors (K-NN) in python and R

---

python basics/contributors.md
python basics/even_or_odd (if-else statement).py
python basics/fabonacci_series.py
python basics/switch_case.py

Created a program to demostrate switch case in python.

Added switch_case.py

---

count the no. of each vowel

this is the code to count the number of vowels in a string.

create count the no. of each vowel

---

machine learning basics/simple_linear_regression.py

Added an example for simple linear regression for #26

Added example for simple linear regression 

---

machine learning basics/text_mapping.py

Sequence builder for text data into sequence for Deep Learning tasks.

Text mapping to sequence for Deep Learning

---

python basics/dictionary.py

Presents simple operations and functions with dictionaries.

Python Dictionary added to python basics

---

armstrong no.

i created a program to find a number is armstrong no. or not

armstrong no.

---

README.md

Added Free Machine Learning Courses to README (Stanford and Columbia University courses). Addresses #27

Added Free Machine Learning Courses to README

---

machine learning basics/SVM/iris_classification_svm.py
machine learning basics/SVM/readme.md
machine learning basics/iris_classification_svm.py

Issue addressed : #26 
SVM code added along with readme file

Svm code added

---

python basics/decorators.py
python basics/generators.py

Added code for generators in python basics

Added code for generators

---

machine learning basics/Readme.md

Updated supporting data for ML, Deep Learning and Data Science learning curve.

Added reference links for ML roadmap

---

machine learning basics/Readme.md

Contributor Update

---

python basics/args_distance_convertor.py

A Python example of reading in arguments with args parse, shows help option, locking down to option and setting different input types

Add an example for parsing arguments

---

machine learning basics/sentiment_analysis_imdb.ipynb

This is a simple sentiment analysis pipeline for IMDB movie reviews dataset.

add sentiment analysis notebook

---

rock, paper, scissor

this is the program for rock, paper, scissor

create rock, paper,scissor program

---

README.md

just added a link in README.md

---

python basics/.idea/workspace.xml
python basics/file_operations.py
python basics/overwrite_file.txt
python basics/test_file.txt

Added a demonstration of basic operations in files. Addresses #3

Added demo for basic operations on files

---

machine learning basics/XGBoost.ipynb

Added a new jupyter notebook for the basics of XGboost model along with its implementation.

Adding jupyter notebook for basics of XGBoost

---

KMP_Algoritm.py

I have added a KMP Algorithm . 
This algorithm used for searching a pattern/string in a another text/string using an array of prefixes and suffixes. It overrides the Naive algorithm and improves the worst case to O(n).

Implemented KMP algorithm in python
